coverage:
  range: 50..70
  round: down
  precision: 2
  status:
    project:
      default:
        target: 50%
    patch:
      default:
        target: 50%

ignore:
  - "src/main/java/app/carparksg/api/model/LtaCarpark.java"
  - "src/main/java/app/carparksg/api/model/LtaAvailability.java"